### ISSUE TITLE
Restore automatic building of documentation

### ISSUE THREAD

**Issue by zonca** [oirlab/liger_iris_pipeline#74]
Once we have the test cases all running, we should restore the documentation build.

I am not using readthedocs because it had trouble building `iris_readout`, I am using directly Github Actions to also build the docs. This is convenient because you only need to worry about making 1 CI environment to work.

Here is the configuration I was using before:

```yaml
      - name: Build docs
        if: ${{ matrix.python-version==3.11 }}
        run: |
          python -m pip install -r docs/requirements.txt && cd docs && make html
      - name: Deploy
        if: ${{ matrix.python-version==3.11 && contains(github.ref, 'master') }}
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: master
          folder: docs/_build/html
          repository-name: oirlab/iris-pipeline
          ssh-key: ${{ secrets.DEPLOY_KEY }}
```

It is just building with sphynx and pushing to github pages.
